name: Testing backend

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]
  schedule:
    - cron: '0 7,14 * * *'
      branches: [ main, testing ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        torch-version: ["1.10.2"]
        torchvision-version: ["0.11.3"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install numpy==1.22 opencv-python Pillow==9.0 scipy==1.8 requests
        pip install Flask==2.0.2 Flask-cors==3.0

    - name: Install PyTorch ${{ matrix.torch-version }}+cpu
      run: |
        pip install torch==${{ matrix.torch-version}}+cpu torchvision==${{ matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        python -m pytest test/unit_tests --cov=src --cov=ai_filters --cov=classic_filters

    - name: Run integration tests
      run: |
        python -m pytest test/integr_tests
